### PR TITLE
Tag for release v1.2.0

### PR DESCRIPTION
**Pull request by ese**
Prepare for tag release v1.2.0

### CODE REVIEW

**Review by dmamolina — APPROVED** [review]

**Comment by samof76** [comment]
@ese can we hold this there are some bugs i am looking at... can we after those fixes?

Example: https://github.com/spotahome/redis-operator/blob/master/operator/redisfailover/service/generator.go#L469

Not sure why `ConfigCopy` should have `ContainerSecurityContext` when we already have it defined as part of the CRD, here - https://github.com/spotahome/redis-operator/blob/master/api/redisfailover/v1/types.go#L81

**Comment by samof76** [comment]
@ese I guess its ok... this is getting passed to the initContainer. This will not block anything we could merge this. But a question to see should have do this #469 ?

**Comment by ese** [comment]
> @ese can we hold this there are some bugs i am looking at... can we after those fixes?

Yes, I am also doing testing on current build so just getting ready here the changes for the final release but we will hold until we fix that issues

> Example: https://github.com/spotahome/redis-operator/blob/master/operator/redisfailover/service/generator.go#L469
> 
> Not sure why `ConfigCopy` should have `ContainerSecurityContext` when we already have it defined as part of the CRD, here - https://github.com/spotahome/redis-operator/blob/master/api/redisfailover/v1/types.go#L81

**Comment by samof76** [comment]
@ese i do not think there is an issue. go ahead and release.

**Comment by samof76** [comment]
@ese Awesome

**Pull request merged**
