### PR TITLE
Add ability to paste custom annotations to CRD in Helm chart

### PR DESCRIPTION
**Pull request by EsDmitrii**
Hi!
I faced issues when tried to deploy redis-operator via ArgoCD
```
CustomResourceDefinition.apiextensions.k8s.io "redisfailovers.databases.spotahome.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```
To fix this issue I need to paste special annotation for ArgoCD.
I can't do this via values file, and I need to download chart locally, make changes and deploy.
I added ability to add special custom annotations via `values.yaml` file.

### CODE REVIEW

**Review by ese — APPROVED** [review]

**Comment by ese** [comment]
Thanks!, Im happy to merge this if you merge with master and fix the conflicts

**Comment by liupeng0518** [comment]
merged this pr has err:
```
❯ helm upgrade --install redis-operator redis-operator/redis-operator --version 3.3.0                                                                                          ─╯
Error: failed to install CRD crds/databases.spotahome.com_redisfailovers.yaml: error parsing : error converting YAML to JSON: yaml: line 4: did not find expected node content
helm.go:84: [debug] error parsing : error converting YAML to JSON: yaml: line 4: did not find expected node content
```

**Comment by sergey-kudriavtsev** [comment]
@EsDmitrii  Please check the work

**Comment by EsDmitrii** [comment]
sorry for the long response, I'm working on it

**Pull request merged**
