### PR TITLE
Upgrade kooper (v2) and kubernetes (v1.22)

### PR DESCRIPTION
**Pull request by ese**
### Description

Update kooper library to v2 to unblock the update of underlying Kubernetes libraries.
CRD handling has been removed and must be managed outside the operator, it will be included in the chart in next PRs

Changes proposed on the PR:
-  Update kooper to v2
-  Update kubernetes libs to v1.22
-  Remove CRD handling

### CODE REVIEW

**Review by javespi — APPROVED** [review]

**Comment by yxxhero** [comment]
@ese Looking forward to the merger. Is there an approximate time? Thanks very much.

**Review by elacacio — APPROVED** [review]
🙃

**Review by manurosa — APPROVED** [review]
👍

**Comment by ese** [comment]
> @ese Looking forward to the merger. Is there an approximate time? Thanks very much.

If all the testing goes well we can do a release next week

**Pull request merged**
