### PR TITLE
adding "ServiceAccountName" field to sentinel & redis

### LINKED ISSUE #301: Ability to use a custom Service Account for rfs and rfr deployment/statefulset
Currently the deployments and statefulsets created by the operator use the `default` Service Account, in many scenarios we need to use a non-default SA.

The CRD should allow to specify a custom Service Account Name that will be used in the generated manifests (deployment, statefulsets).

The operator should not need to create the SA, just allow to specify it in the generated manifest specs.

### PR DESCRIPTION
**Pull request by dkulchinsky**
Fixes #301 .

### CODE REVIEW

**Comment by dkulchinsky** [comment]
update the README, also referenced Priority Class that was added in #282 

@ese hope you'll have a chance to take a look and merge if this is OK.

**Comment by dkulchinsky** [comment]
@ese hoping to hear back in case you have some cycles to review & merge this PR?

**Comment by dkulchinsky** [comment]
Folks, just trying to figure out if this project is still actively maintained? there hasn't been any activity since last August and just looking to understand if there's still commitment/interest to keep this maintained.

We appreciate the work and effort being put into this project and use it mostly with great success, we do have some outstanding issues which we would like to push upstream, like this PR and other pending PRs we're waiting to get merged, we're currently considering forking the project to be able to maintain it locally until there's some clarity about the future of the project.

In any case, thank you all again for this project and your work, hope to hear back from you and more than happy to help push here as much as we can.

**Comment by ese** [comment]
@dkulchinsky Thanks for the PR and sorry for the delay to answer you. We have had reduced the workforce available for the project and probably we will not push as hard as before but we will be taken care of the contribution and polishing some features.

**Review by ese — APPROVED** [review]

**Comment by dkulchinsky** [comment]
Hi @ese, good to hear from you and thanks for reviewing and merging the PR, we hope to contribute more upstream.

**Comment by dkulchinsky** [comment]
@ese any timeline for when you might cut a new release with the latest changes that were merged?

**Pull request merged**
