### PR TITLE
Add loop to ensure proper response

### PR DESCRIPTION
**Pull request by minac**
Fixes https://github.com/spotahome/redis-operator/issues/269.

Changes proposed on the PR:
- Add a `while` loop when determining the current `master` pod name in shutdown script
- Add a `while` loop when asking the Sentinels to perform a `failover` in the shutdown script
- Add 3 retries as a circuit breaker

### CODE REVIEW

**Comment by minac** [comment]
This repository seems unmaintained. Closing.

**Comment by dkulchinsky** [comment]
Hey @minac, my PR (#303) was just reviewed and merged, might want to reconsider and open it.

**Comment by minac** [comment]
Thank you @dkulchinsky. We have since forked the project and made changes on our side. Maybe one day we can loop them back to this repository if it becomes alive again.

**Comment by dkulchinsky** [comment]
> Thank you @dkulchinsky. We have since forked the project and made changes on our side. Maybe one day we can loop them back to this repository if it becomes alive again.

Cool 👍🏼 we were planning to do the same at some point but then got this comment from @ese https://github.com/spotahome/redis-operator/pull/303#issuecomment-885923495 looks like they do intend to keep it alive and accept contributions.

**Pull request closed without merging**
