### PR TITLE
update default image

### PR DESCRIPTION
**Pull request by jiuker**
The alpha version looks like it can be replaced with the latest official version

Fixes # .

Changes proposed on the PR:
- change default redis image

### CODE REVIEW

**Comment by samof76** [comment]
@jiuker why not alpine?

**Comment by jiuker** [comment]
> @jiuker why not alpine?

I think the stable version is more stable than the alpha version.

**Comment by jiuker** [comment]
> @jiuker why not alpine?

I think the stable version is more stable than the alpha version.

**Comment by samof76** [comment]
@jiuker alpine is not alpha, but nevertheless bullseye is a better proposition.

**Comment by ThomasTosik** [comment]
This would be major change from Alpine to Debian. I dont see any value in it. The alpine versions are also smaller.

**Pull request closed without merging**
