### PR TITLE
support volumeCliamTemplates

### PR DESCRIPTION
**Pull request by sillydong**
add volumes, volumeMounts, volumeClaimTemplates
remove dataVolume

Fixes # .

Changes proposed on the PR:
- add more configuration for redis store

### CODE REVIEW

**Comment by sillydong** [comment]
We met a demand to use PersistentVolumeClaim in redis store, so I added more configuration for this demand. 

PS: dataVolume is removed as there is no need for dataVolume, I add volumes for it.

**Comment by sillydong** [comment]
If there is anything wrong, please tell me. Thanks! @jchanam

**Comment by jchanam** [comment]
Hi @sillydong,

First of all, sorry for the delay.

The point of having the Custom Resource, is making the creation of a Redis as easy as possible. I think doing this the way you're proposing, is maybe adding much complexity.

I'd do it less configurable. Basically, allowing having an empty-dir (by default), or a Persistent Volume Claim.

What do you think? As this is becoming a priority for us, we have been thinking on developing this functionality. Would you mind if I develop it and send a PR?

Thanks again for your interest!

**Comment by sillydong** [comment]
Great, hoping we can use it soon!

**Comment by ese** [comment]
closed in favor of #68

**Pull request closed without merging**
