### PR TITLE
[Missed]Sentinel extra volumes 

### PR DESCRIPTION
**Pull request by samof76**
Fixes #000 .

Missed to add `extraVolumes` and `extraVolumeMounts` to sentinel deployments

### CODE REVIEW

**Review by ese — APPROVED** [review]

**Comment by ese** [comment]
Thanks for all the effort @samof76

**Comment by samof76** [comment]
@ese  Can we do an `rc1`?

**Comment by ese** [comment]
sure

**Comment by ese** [comment]
@samof76 https://github.com/spotahome/redis-operator/releases/tag/v1.2.0-rc1

**Pull request merged**
