### PR TITLE
Add sidecars and initcontainers

### LINKED ISSUE #187: How to add sidecar container in  redis-data-rfr-redisfailover pod
How to add sidecar container in  redis-data-rfr-redisfailover

### PR DESCRIPTION
**Pull request by samof76**
Fixes #187

Changes proposed on the PR:
- Adds sidecar
- Adds initcontainer

### CODE REVIEW

**Comment by ese** [comment]
Thanks @samof76, what is the use case you are trying to resolve with this feature? It could be something that we should abstract and manage directly from the operator.
Anyways I'm not against the feature but I would name the `sidecars` property as `extraContainers`

**Comment by samof76** [comment]
We require addition containers for
- manage failover to be propagated to the DNS
- manage periodic backup of the RDB files to blob storages
- Some other additional tasks

**Comment by samof76** [comment]
@ese `sidecars` -> `extraContainers`

**Comment by ese** [comment]
Thanks @samof76, could you resolve conflicts and generate CRDs with changed spec?

**Review by ese — APPROVED** [review]

**Pull request merged**
