### PR TITLE
Feature: Adding capabilility to define custom probes

### PR DESCRIPTION
**Pull request by samof76**
# Feature: Custom Probes

Both Redis and Sentinel will have the capability to now define...
- `customLivenessProbe`:  Your own Liveness probe
- `customReadinessProbe`: Your own Readiness probe
- `customStartupProbe`: Your own Startup probe

### CODE REVIEW

**Comment by samof76** [comment]
@ese can you please review this?

**Comment by samof76** [comment]
@ese a couple of things I have done fix...
... 1. The issue of the alpha fields.
Downgraded k8s.io/api and k8s.io/apimachinery

```
go get -v k8s.io/api@v0.24.4
go get k8s.io/apimachinery@v0.24.4
go mod tidy
go mod vendor
```

And then generated CRD file. 

... 2. The minikube new version has an issue with the cni plugin so downgraded it, as well.

**Comment by samof76** [comment]
@ese please review this?

**Comment by jonathon2nd** [comment]
I am attempting to use these, and they are not working
CHART: redis-operator:3.2.9

Wanting to set the following under redis so it stops trying to use the hostname
```

    customLivenessProbe:
      exec:
        command:
          - sh
          - '-c'
          - >-
            redis-cli -h 127.0.0.1 -p 6379 ping --user pinger --pass
            pingpass --no-auth-warning
```

**Pull request merged**
