### PR TITLE
[feature]set loglevel as flag

### PR DESCRIPTION
**Pull request by lvyanru8200**
Signed-off-by: yanru.lv <yanru.lv@daocloud.io>

Fixes # .

Changes proposed on the PR:
-  set loglevel as a flag

### CODE REVIEW

**Comment by lvyanru8200** [comment]
https://github.com/spotahome/redis-operator/issues/507

**Comment by ese** [comment]
Thanks!

**Review by ese — APPROVED** [review]

**Comment by rdxmb** [comment]
Can this be set via `command` in the kubernetes-manifest ? What are the values allowed for this flag?

**Pull request merged**
