### PR TITLE
198 bootstrap node

### LINKED ISSUE #198: Question: Starting RedisFailover to replicate from existing redis instance
Hey all,

Quick question: I'm wondering if there is a known workaround/hack to put in place that will allow me to spinup a new `RedisFailover` instance that replicates from a pre-existing Redis instance?

I'm hoping to launch a `RedisFailover` instance soon and it would very convenient to not lose any existing data we have. Right now the operator is thwarting any of my attempts to manually set a master.

Just curious if this use case has been thought up / a known workaround is possible!

Thanks!

P.S - setting `slaveof` in the redis config seems to be directly unsupported (this is what I hoped would work out of the gate)
```
time="2019-11-04T20:02:59Z" level=warning msg="error processing aj-redis/redisfailover job (requeued): ERR Unsupported CONFIG parameter: slaveof" controller=redisfailover operator=redis-operator src="generic.go:224"
```

### PR DESCRIPTION
**Pull request by alecjacobs5401**
Fixes #198 

Changes proposed on the PR:
- new top level key in `RedisFailover.spec` called `bootstrapNode`
  - accepts the following keys:
    - `host` **(required)**
    - `port` _(optional)_
    - `allowSentinels` _(optional)_

## PR Details
This PR adds the ability for users to define a `bootstrapNode` to start their `RedisFailover` instance. 
By default, the only requirement is a host IP. (note: a static Service ClusterIP **will work** for this use case). 

The README updates should provide some more context on the overall scope of change.

That being said, there are some things that I'm not super stoked about in this PR. I didn't want to change/update too much of what was already put in place, so I added some more methods to various clients (mainly the Redis service client) to account for a custom `port` to be provided.

Is this the right path to have taken? I took the path of least resistance to introduce _less_ overall scope of changes.

Super happy to hear of any feedback! Thanks!

### CODE REVIEW

**Comment by alecjacobs5401** [comment]
@chusAlvarez thanks!

I totally agree about taking a struct approach. Much better for flexibility and can provide a solid contract.

**Comment by jawabuu** [comment]
@alecjacobs5401 @chusAlvarez 
How would one provide auth password for the external redis?

**Comment by alecjacobs5401** [comment]
@jawabuu I believe that the bootstrap node will use any [existing authentication that is configured](https://github.com/spotahome/redis-operator#enabling-redis-auth)

**Comment by jawabuu** [comment]
Thanks @alecjacobs5401
So it would use the password to connect to to the external redis and also require that same password when connecting to it?

**Comment by alecjacobs5401** [comment]
@jawabuu Correct. That would imply that you are sharing a password between the external redis and the redis that is managed by the operator.

If you needed different credentials, then likely there would be a change necessary to the operator to support that.

I can't say with 100% certainty though, you would likely need to test it out for yourself to see.

**Comment by jawabuu** [comment]
Thanks @alecjacobs5401 My only concern was being able to connect to the external redis that is behind auth.

**Comment by jawabuu** [comment]
Hey @alecjacobs5401 How would you switch over to RedisFailover once copy is caught up?

**Comment by alecjacobs5401** [comment]
@jawabuu Apologies for a late response here

You should be able to update the `redisfailover` config to remove the `bootstrapNode` config and the operator should take over.

I would recommend testing in your own environment first as well.

**Comment by jawabuu** [comment]
Hey @alecjacobs5401 
Can I reach you on slack?
I haven't been able to get the bootstrap feature working
https://github.com/spotahome/redis-operator/issues/311

**Pull request merged**
