### PR TITLE
Configurable component name in helm chart

### PR DESCRIPTION
**Pull request by terjesannum**
Use component name from values instead of hardcoded "app"

### CODE REVIEW

**Comment by ese** [comment]
Thanks @terjesannum. What is porpose of this change? IMHO this label should be always the same. Maybe it would be more meaningful component `controller`

**Comment by terjesannum** [comment]
For e.g. metrics and logs these labels are usually indexed, and the purpose is to have a more descriptive value there. How the value is used can vary from deployment to deployment, that's why I made it configurable. "app" or "controller" could well be the default, but it would be nice to be able to change that without creating a forked version the chart.

**Comment by ese** [comment]
Just trying to understand. Why is not valid `release` label for this porpose? https://github.com/spotahome/redis-operator/blob/master/charts/redisoperator/templates/_functions.tpl#L10

**Comment by terjesannum** [comment]
This is what I've planned for my next PR for this chart, the possibility to add labels and annotations :) That can of course also be used for the use cases I mentioned, but still there might be cases where you want to override and have a more descriptive value for the container name. I can't see why the chart should not support that.

**Comment by Kyrremann** [comment]
Has there been any decision about this? Will you allow it and merge?

**Comment by jchanam** [comment]
I think this is a good idea, but I'd go for the approach proposed by @ese, allowing to configure freely the labels and leaving the ones that are already set as default so there are no breaking changes.

About changing the container name, Is that for any reason in particular?

What do you think @terjesannum?

**Comment by terjesannum** [comment]
An option to add labels and annotations is a good thing, but I still don't think "app" is a good name to use for the container. If you see changing the container name as a breaking change, the default in `values.yaml` could well be "app" so updating the chart won't change anything if you don't override it.

Below is an example list of containers running in a cluster, the pod installed from the redisoperator is the only one without a descriptive container name...

```
$ kubectl get pods -o=custom-columns=POD:.metadata.name,CONTAINERS:.spec.containers[*].name
POD                                                              CONTAINERS
coredns-68db7dd64d-4zbtx                                         coredns
coredns-68db7dd64d-gmd9m                                         coredns
heapster-564fdf68f5-zq6pl                                        heapster
kube-apiserver-foo.local                                         kube-apiserver
kube-controller-manager-foo.local                                kube-controller-manager
kube-scheduler-foo.local                                         kube-scheduler
kubernetes-dashboard-58f9cc87fd-zpl9k                            kubernetes-dashboard
monitoring-influxdb-76dbc4c7cd-zckf6                             influxdb
prometheus-prometheus-alertmanager-7c48ff67d6-vfmnm              prometheus-alertmanager,prometheus-alertmanager-configmap-reload
prometheus-prometheus-kube-state-metrics-7b7cfc5dd8-nmpl7        prometheus-kube-state-metrics
prometheus-prometheus-node-exporter-5rq9r                        prometheus-node-exporter
prometheus-prometheus-node-exporter-7b5gr                        prometheus-node-exporter
prometheus-prometheus-node-exporter-cwxgd                        prometheus-node-exporter
prometheus-prometheus-pushgateway-68966b6ff7-lv2ck               prometheus-pushgateway
prometheus-prometheus-server-5889f556b6-pfnjs                    prometheus-server-configmap-reload,prometheus-server
redisoperator-redisoperator-79c8786f74-dcj7j                     app
rook-agent-4kjxj                                                 rook-agent
rook-agent-b9p4r                                                 rook-agent
rook-agent-bszhl                                                 rook-agent
rook-operator-68b7496879-mqtlh                                   rook-operator
tiller-deploy-685fcff864-vgdqc                                   tiller
traefik-ingress-controller-4dpfv                                 traefik-ingress-lb
traefik-ingress-controller-66q45                                 traefik-ingress-lb
traefik-ingress-controller-8hdh2                                 traefik-ingress-lb
```

**Comment by jchanam** [comment]
Hi @terjesannum,

There are two different things here:
* On one hand, there is the labels (and selector). On that case, changing them is a breaking change for the Redis-Operator already deployed.
* On the other hand, there is the name of the container. That is not a breaking change and I'm ok with your proposal.

What I'm saying is that if you want to change the labels, I recommend to use the idea given by @ese. Always leaving as default the labels already used.

KR,

**Pull request merged**
