### PR TITLE
Removed prometheus service

### LINKED ISSUE #44: Move export annotation to pods
I've been working some more on the Redis exporter annotation, and I want to move the annotation to the pods that have the exporter, and delete the extra unnecessary service that we currently have.

There is also a bug currently, where Prometheus is targeting both the ports that are exposed. I started looking into that, and that's when I found out that it was recommended to annotate the pods instead of have the service. 

Some arguments for this is here:
https://groups.google.com/forum/#!msg/prometheus-users/jDEzVHUUFzw/pdNgbVGsBQAJ

I'll make a PR for it tomorrow. And we can discuss this some more.

### PR DESCRIPTION
**Pull request by Kyrremann**
Fixes #44.

Changes proposed on the PR:
- Removes redis service for exporter
- Add Prometheus annotation to the exporter pod

### CODE REVIEW

**Comment by Kyrremann** [comment]
Okay, it took me two weeks to create this PR, but here it is. I'm not 100% sure I managed to create all the mocks, and generate all the correct code, but it works in my cluster.

**Comment by ese** [comment]
Thanks @Kyrremann. I think the service is still needed if you are using prometheus-operator where you do discovery at service level not pod. thoughts @slok ?

**Comment by slok** [comment]
@ese Correct, [ServiceMonitor](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#servicemonitor) is the resource that needs the services to get the endpoints from it and monitor.

I wouldn't remove the service, lot's of people use [prometheus-operator](https://github.com/coreos/prometheus-operator)(this includes us) in their clusters and if we remove the service people would need to add manually, making the operator usage less automated, and the aim of the operators/controllers is to automate these things.

**Comment by Kyrremann** [comment]
@sillydong This PR dosen't remove the redis-exporter, just the service that is exposed.

@ese and @slok: Okay, wasn't aware of the `ServiceMonitor`, we scrape on pod level, and hence the service is just adding another layer.

Would a solution where we can add annotation via the operator, and also an option to not create the exporter-service be a better solution?

Annotation via the operator would also be good for adding more specific information, for example teams and similar.

**Comment by Kyrremann** [comment]
Okay, had a talk with my team, and did some testing. It seems that we get the data we need (and more) from just the service.

So we can close this PR & issue. Less hassle for everyone.
Thanks for the help!

**Pull request closed without merging**
