### PR TITLE
[fix] example yaml image version change

### PR DESCRIPTION
**Pull request by lvyanru8200**
Signed-off-by: yanru.lv <yanru.lv@daocloud.io>

Fixes # .

Changes proposed on the PR:
- example/operator deploy yaml change
- 
-

### CODE REVIEW

**Comment by lvyanru8200** [comment]
https://github.com/spotahome/redis-operator/issues/515

**Comment by samof76** [comment]
@ivan1900 this is a chicken and egg issue. So its better to keep it as latest.

**Comment by lvyanru8200** [comment]
> @lvyanru8200 this is a chicken and egg issue. So its better to keep it as latest.

you are right

**Comment by samof76** [comment]
@lvyanru8200 looks good!

**Review by ese — APPROVED** [review]

**Comment by haslersn** [comment]
It's not a good idea to keep it as `latest`, because that way you cannot deploy a certain version by downloading the example from the respective git tag. Furthermore, for people who download the example and deploy it via a CI/CD tool, it will most likely break at some point, because a new version of the operator might require different manifests, e.g., more RBAC permissions. Please note that no other major kubernetes operator vendor puts the latest tag in deployment examples; see, e.g., https://github.com/kubernetes/ingress-nginx/blob/2ea010986f8348b259468506a3118dcc34f54b38/deploy/static/provider/baremetal/deploy.yaml#L452.

**Comment by haslersn** [comment]
Adding to my previous comment: It's not only an issue when deploying via CI/CD. Even when simply restarting the operator on a node where the image is not yet present, it will of course pull the `latest` tag. Disaster is inevitable as soon as a new operator version requires different manifests, e.g., more RBAC permissions or a new CRD version.

**Pull request merged**
