### PR TITLE
[Feature]: Add topology spread constraints.

### PR DESCRIPTION
**Pull request by samof76**
Fixes #000 .

Changes proposed on the PR:
- Add topologySpreadContraints for redis and sentinel
- Add example to showcase how to use it

### CODE REVIEW

**Comment by samof76** [comment]
@ese can you please review this?

**Review by ese — APPROVED** [review]

**Comment by ese** [comment]
Thanks! good feature. Happy to merge as soon conflicts as resolved

**Review by ese — APPROVED** [review]

**Comment by samof76** [comment]
@ese Done

**Comment by ese** [comment]
Sorry, we end with conflicts again :grimacing:

**Comment by samof76** [comment]
Done @ese

**Pull request merged**
