### PR TITLE
Implement redis auth

### LINKED ISSUE #66: redis auth?
Is there a way to setup redis with auth and have sentinel use that auth to connect?

### PR DESCRIPTION
**Pull request by hoffoo**
Fixes #66 

Changes proposed on the PR:
- add a secretPath which pointing to a secret with a "password" field
- populate redis and sentinel configs with value from said path

I avoided tackling the more complex questions of reloading on change and etc, I hope this is good enough for most use cases.

### CODE REVIEW

**Comment by hoffoo** [comment]
@jchanam can I get a review on this? sorry i opened the PR prematurely but was having trouble running the tests locally

**Comment by hoffoo** [comment]
@slok @ese could I get some feedback on this PR?

**Comment by ese** [comment]
Thanks @hoffoo for your PR. I will take a look

**Comment by hoffoo** [comment]
I just realized this does not work correctly when managing multiple instances, please hold off on the review and ill fix

**Comment by hoffoo** [comment]
@ese sorry about that, its fixed now and ready for your review again

**Comment by danielllek** [comment]
I'm evaluating redis-operator and looks great, but lacks this feature - in case you need some assistance, I'm willing to help ;)

**Comment by hoffoo** [comment]
@danielllek thats great, I've tested it a bunch and I think its ready. If you want to test you can build the image and give it a shot. getting an image is easy, just clone and `make image`

**Comment by danielllek** [comment]
Cool, I'll try it on Monday.

**Comment by danielllek** [comment]
@hoffoo 
As far as I've read the code right, yaml should look like this, right?
```
apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover
spec:
  sentinel:
    replicas: 3
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 100Mi
  redis:
    replicas: 3
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 400m
        memory: 500Mi
  auth:
    secretpath: secret
```

First test I've made was to run it without creating `secret` - shouldn't it fail to deploy if secret doesn't exists?

**Comment by hoffoo** [comment]
Without secret it kubectl apply will work but there will be an error in the controller log

in your config secretpath should be `secretPath`

Thanks for doing this, ill add to the readme in my PR

**Comment by danielllek** [comment]
@hoffoo One step further, but it doesn't work with operator installed from helm with `rbac.install: true`

I've tried creating redisfailover in the same namespace as redis-operator or completly different - no change:
```
time="2019-10-10T10:58:36Z" level=info msg="service created" namespace=redis-operator service=k8s.service serviceName=rfs-redisfailover src="service.go:59"
time="2019-10-10T10:58:36Z" level=warning msg="error processing redis-operator/redisfailover job (requeued): secrets \"secret\" is forbidden: User \"system:serviceaccount:redis-operator:redis-operator-redisoperator\" cannot get resource \"secrets\" in API group \"\" in the namespace \"redis-operator\"" controller=redisfailover operator=redis-operator src="generic.go:224"
time="2019-10-10T10:58:36Z" level=warning msg="error processing redis-operator/redisfailover job (requeued): secrets \"secret\" is forbidden: User \"system:serviceaccount:redis-operator:redis-operator-redisoperator\" cannot get resource \"secrets\" in API group \"\" in the namespace \"redis-operator\"" controller=redisfailover operator=redis-operator src="generic.go:224"
time="2019-10-10T10:58:36Z" level=warning msg="error processing redis-operator/redisfailover job (requeued): secrets \"secret\" is forbidden: User \"system:serviceaccount:redis-operator:redis-operator-redisoperator\" cannot get resource \"secrets\" in API group \"\" in the namespace \"redis-operator\"" controller=redisfailover operator=redis-operator src="generic.go:224"
time="2019-10-10T10:58:36Z" level=error msg="Error processing redis-operator/redisfailover: secrets \"secret\" is forbidden: User \"system:serviceaccount:redis-operator:redis-operator-redisoperator\" cannot get resource \"secrets\" in API group \"\" in the namespace \"redis-operator\"" controller=redisfailover operator=redis-operator src="generic.go:224"
```

**Comment by hoffoo** [comment]
@danielllek great find, i updated the helm chart, helm upgrade should apply it

for the record: the secret needs to be in the same namespace as the redisfailover object (not the controller namespace)

**Comment by danielllek** [comment]
Works now, thanks!

One more question on the side, operator logs every 30s such log, is it normal?
```
time="2019-10-11T09:08:49Z" level=info msg="configMap updated" configMap=rfs-redisfailover namespace=platform-local service=k8s.configMap src="configmap.go:76"
time="2019-10-11T09:08:49Z" level=info msg="configMap updated" configMap=rfr-s-redisfailover namespace=platform-local service=k8s.configMap src="configmap.go:76"
time="2019-10-11T09:08:49Z" level=info msg="configMap updated" configMap=rfr-redisfailover namespace=platform-local service=k8s.configMap src="configmap.go:76"
time="2019-10-11T09:08:49Z" level=info msg="podDisruptionBudget updated" namespace=platform-local podDisruptionBudget=rfr-redisfailover service=k8s.podDisruptionBudget src="poddisruptionbudget.go:77"
time="2019-10-11T09:08:49Z" level=info msg="statefulSet updated" namespace=platform-local service=k8s.statefulSet src="statefulset.go:101" statefulSet=rfr-redisfailover
time="2019-10-11T09:08:49Z" level=info msg="podDisruptionBudget updated" namespace=platform-local podDisruptionBudget=rfs-redisfailover service=k8s.podDisruptionBudget src="poddisruptionbudget.go:77"
time="2019-10-11T09:08:49Z" level=info msg="deployment updated" deployment=rfs-redisfailover namespace=platform-local service=k8s.deployment src="deployment.go:101"

time="2019-10-11T09:09:19Z" level=info msg="configMap updated" configMap=rfs-redisfailover namespace=platform-local service=k8s.configMap src="configmap.go:76"
time="2019-10-11T09:09:19Z" level=info msg="configMap updated" configMap=rfr-s-redisfailover namespace=platform-local service=k8s.configMap src="configmap.go:76"
time="2019-10-11T09:09:19Z" level=info msg="configMap updated" configMap=rfr-redisfailover namespace=platform-local service=k8s.configMap src="configmap.go:76"
time="2019-10-11T09:09:19Z" level=info msg="podDisruptionBudget updated" namespace=platform-local podDisruptionBudget=rfr-redisfailover service=k8s.podDisruptionBudget src="poddisruptionbudget.go:77"
time="2019-10-11T09:09:19Z" level=info msg="statefulSet updated" namespace=platform-local service=k8s.statefulSet src="statefulset.go:101" statefulSet=rfr-redisfailover
time="2019-10-11T09:09:19Z" level=info msg="podDisruptionBudget updated" namespace=platform-local podDisruptionBudget=rfs-redisfailover service=k8s.podDisruptionBudget src="poddisruptionbudget.go:77"
time="2019-10-11T09:09:19Z" level=info msg="deployment updated" deployment=rfs-redisfailover namespace=platform-local service=k8s.deployment src="deployment.go:101"
```

**Comment by hoffoo** [comment]
@danielllek could you test again and make sure sentinel works? found a problem which causing sentinels to not have the auth and not reach a quorum - fixed in the latest commit.

**Comment by danielllek** [comment]
@hoffoo works :+1:

**Comment by hoffoo** [comment]
great! @ese this is ready again - I am using it in a few places and @danielllek has tested it out as well

**Comment by ese** [comment]
Thanks a lot @hoffoo and @danielllek. I'm taking time to have this reviewed this week.

**Comment by paulcostinean** [comment]
Is there anything left for this to be merged and included in a release? currently using it and there are no apparent issues 👍

**Comment by danielllek** [comment]
/me is also waiting. I'm also using it from my own images.

**Pull request merged**
